type: rpm-ostree
install:
  - fastfetch
  - libxcrypt-compat
  - openssl
remove:
  - default-editor
  - fedora-flathub-remote
  - firefox
  - firefox-langpacks
  - htop
  - nano
  - nano-default-editor
  - nvtop
  - vim-common
  - vim-data
  - vim-enhanced
  - vim-filesystem
  - vim-minimal
