type: rpm-ostree
repos:
  - https://copr.fedorainfracloud.org/coprs/ublue-os/staging/repo/fedora-%OS_VERSION%/ublue-os-staging-fedora-%OS_VERSION%.repo
install:
  - btop
  - edk2-ovmf
  - genisoimage
  - gtk4
  - libvirt
  - libxcrypt-compat
  - neovim
  - openssl
  - playerctl
  - ptyxis
  - qemu
  - trash-cli
  - virt-manager
  - virt-viewer
  - vte291
remove:
  - default-editor
  - firefox
  - firefox-langpacks
  - htop
  - nano
  - nano-default-editor
  - nvtop
  - vim-common
  - vim-data
  - vim-enhanced
  - vim-filesystem
  - vim-minimal
