type: rpm-ostree
install:
  - kdialog
remove:
  - ark
  - ark-libs
  - filelight
  - kate
  - kate-plugins
  - kate-krunner-plugin
  - kcharselect
  - kfind
  - kmousetool
  - krfb
  - krfb-libs
  - kwalletmanager5
  - kwrite
  - plasma-welcome
