type: default-flatpaks
notify: true
user:
  repo-name: flathub
  repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
  install:
    - io.gitlab.librewolf-community
    - org.kde.ark
    - org.kde.filelight
    - org.kde.kcalc
    - org.kde.kwalletmanager5
    - org.kde.kwrite
