name: corpsouth-silverblue-main
description: CorpSouth's Opinionated Atomic Silverblue Desktop. Built with Blue-Build.
base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest
modules:
  - from-file: recipes/04-modules/common-files.yml
  - from-file: recipes/04-modules/silverblue-files.yml
  - from-file: recipes/04-modules/common-rpm-ostree.yml
  - from-file: recipes/04-modules/silverblue-rpm-ostree.yml
  - from-file: recipes/04-modules/silverblue-default-flatpaks.yml
  - from-file: recipes/04-modules/common-bling.yml
  - from-file: recipes/04-modules/silverblue-bling.yml
  - from-file: recipes/04-modules/common-fonts.yml
  - from-file: recipes/04-modules/silverblue-fonts.yml
  - from-file: recipes/04-modules/common-systemd.yml
  - from-file: recipes/04-modules/common-signing.yml
